name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-2
      AWS_PROFILE: default
      DOCKER_REGISTRY_BACKEND: 557211737463.dkr.ecr.eu-west-2.amazonaws.com
      IMAGE_NAME: norse3/aidr-bastion-service
      CURRENT_TAG_MICRO: ${{ github.run_number }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Build Docker image
        run: make build-image

      - name: Push Docker image to AWS ECR
        run: make push-image